name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: latest
          check-latest: true

      - run: node -e "var fs=require('fs'),zlib=require('zlib');fs.mkdirSync('dist');fs.writeFileSync('dist/b5b592fa-b2e2-4a47-b2d8-901a2df6f27c.user.js',zlib.brotliDecompressSync(fs.readFileSync('9f093f2c-ff67-4a57-ab05-7245d703d724')))"

      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
